version: "3.8"
services:
  app:
    image: oven/bun:1
    command: sh -c "bun install && bun run dev"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local